# Generated by Django 2.2.4 on 2024-02-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helios_auth', '0002_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='server_user_face_share',
            field=models.ImageField(blank=True, null=True, upload_to='server_user_face_share'),
        ),
    ]
