# Generated by Django 2.2.4 on 2024-02-21 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helios_auth', '0005_auto_20240217_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='basic_is_authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
