# Generated by Django 2.2.24 on 2023-11-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helios', '0005_auto_20210123_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='voting_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='voting_starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
