# Generated by Django 2.2.4 on 2024-01-24 01:44

from django.db import migrations, models
import helios.datatypes


class Migration(migrations.Migration):

    dependencies = [
        ('helios', '0006_auto_20231115_0847'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, helios.datatypes.LDObjectContainer),
        ),
    ]
