AUTH_INDEX="auth@index"
AUTH_LOGOUT="auth@logout"
AUTH_START="auth@start"
AUTH_AFTER="auth@after"
AUTH_WHY="auth@why"
AUTH_AFTER_INTERVENTION="auth@after-intervention"
# AUTH_FACIAL_RECOGNITION="auth@facial-recognition"
# AUTH_FACIAL_RECOGNITION_CLASSIFY="auth@facial-recognition-classify"