# Generated by Django 2.2.4 on 2024-01-27 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_log_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile'),
        ),
    ]
